  name: flutter-check-integration
  on:
    push:
      branches:
      - development
    pull_request:
      branches:
      - development
  jobs:
    check-bats-version:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: flutter --version
      - run: flutter pub get #installing the plugins for the flutter project
      - run: flutter test #running flutter test
        # Add actions to build ios and android
        # - run: flutter build apk #building flutter apk
        # - run: flutter build appbundle #building flutter bundle